// USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
// Cart
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN'
export const ADD_ITEM = 'ADD_ITEM'
export const CLEAR_ITEM_FROM_CARD = 'CLEAR_ITEM_FROM_CARD'
export const REMOVE_ITEM = 'REMOVE_ITEM'

//SHOP
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS'
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START'
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS'
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE'
